/* header-file defining the interface of the dispatcher 					*/
/* the dispatcher contains all functions required to run the 				*/
/* simulated processes 														*/
/* The dispatcher is called in the central scheduling loop. The scheduler	*/
/* must be called to determine, which process to run						*/
/* !!!!!!!!!! Do not edit this file !!!!!!!!!!	*/



#ifndef __DISPATCHER__
#define __DISPATCHER__

#include "bs_types.h"
#include "globals.h"


schedulingEvent_t sim_runProcess(pid_t pid, unsigned quantum); 
/* the process given by the PCB in parameter pProcess is run until			*/
/*		- the given quantum is over,										*/
/*		- an IO event occurs (simulated by random number), or				*/
/*		- the process is complete											*/
/* a quantum value of 0 indicates that no quantum is used (batch scheduling)*/
/* returns the reason for stopping the execution of the process				*/




#endif /* __DISPATCHER__ */
